app/models.py
from app import db


class Task(db.Model):
  id=db.Column(db.Integer,primary_key=True)
  title=db.Column(db.String(100),nullable=False)
  status=db.Column(db.String(20),default="Pending")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()

def create_app():
  app=Flask(__name__)

  app.config['SECRET_KEY']='your-secret-key'
  app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///todo.db'
  app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

  db.init_app(app) 

  from app.routes.auth import auth_bp
  from app.routes.tasks import tasks_bp
  app.register_blueprint(auth_bp)
  app.register_blueprint(tasks_bp)

  return app
  

app/routes/auth.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,session

auth_bp=Blueprint('auth',__name__)

USER_CREDENTIALS={
  'username':'admin',
  'password':'1234'
}

@auth_bp.route('/login',methods=["GET","POST"])
def login():
  if request.method=="POST":
    username=request.form.get('username')
    password=request.form.get('password')

    if username==USER_CREDENTIALS['username'] and password==USER_CREDENTIALS['password']:
      session['user']=username
      flash('Login successful','success')
      return redirect(url_for('tasks.view_tasks'))
    else:
      flash('Invalid username or password','danger')
  return render_template('login.html')



@auth_bp.route('/logout')
def logout():
  session.pop('user',None)
  flash('logged out','info')
  return redirect(url_for('auth.login'))

app/routes/tasks.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,session
from app import db
from app.models import Task

tasks_bp=Blueprint('tasks',__name__)

@tasks_bp.route('/')
def view_tasks():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    
    tasks=Task.query.all()
    return render_template('tasks.html',tasks=tasks)
 
@tasks_bp.route('/add',methods=['GET','POST'])
def add_task():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    
    title=request.form.get('title')
    if title:
        new_task=Task(title=title,status='Pending')
        db.session.add(new_task)
        db.session.commit()
        flash('Task added succesfully','success')

    return redirect(url_for('tasks.view_tasks'))

@tasks_bp.route('/toggle/<int:task_id>',methods=['POST'])
def toggle_status(task_id):
    task=Task.query.get(task_id)
    if task:
        if task.status=='Pending':
            task.status='Working'
        elif task.status=='Working':
            task.status='Done'
        else:
            task.status='Pending'
        db.session.commit()

    return redirect(url_for('tasks.view_tasks'))
                    
@tasks_bp.route('/clear',methods=['POST'])
def clear_tasks():
    Task.query.delete()
    db.session.commit()
    flash('All tasks cleared!','info')
    return redirect(url_for('tasks.view_tasks'))

@tasks_bp.route('/update/<int:task_id>', methods=['GET', 'POST'])
def update_task(task_id):
    task = Task.query.get_or_404(task_id)
    if request.method == 'POST':
        new_title = request.form.get('title')
        if not new_title:
            flash('Title cannot be empty', 'danger')
            return redirect(request.url)

        task.title = new_title
        db.session.commit()
        flash('Task updated successfully', 'success')
        return redirect(url_for('tasks.view_tasks'))

    return render_template('update.html', task=task)


@tasks_bp.route('/delete/<int:task_id>', methods=['GET', 'POST'])
def delete_task(task_id):
    task = Task.query.get(task_id)
    db.session.delete(task)
    db.session.commit()
    flash('Task deleted successfully!', 'info')
    return redirect(url_for('tasks.view_tasks'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{%block title%}To-Do App{%endblock%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <header>
        <div class="container">
            <h1>MY-TO-DO-APP</h1>
            <nav>
                <a href="{{ url_for('auth.login') }}">Login</a>
               
                <a href="{{ url_for('tasks.view_tasks') }}">Tasks</a>
                {%if 'user' in session %}
                <a href="{{ url_for('auth.logout') }}">LogOut</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <main class="container">
        {% with messages=get_flashed_messages(with_categories=True)%}
        {% for category, message in messages%}
        <div class="flash {{category}}">{{message}}</div>
        {% endfor %}
        {% endwith %}

        {%block content%}{%endblock%}
    </main>
    <footer >
<div class="container">
    <p>&copy;{{2025}} My flask TO-Do-APp</p>
</div>
    </footer>
</body>

</html>

app/templates/login.html
{% extends 'base.html' %}
{%block title%}LOGIN{%endblock%}
{% block content %}

<div class="login-box">
    <h2>LOGIN</h2>
    <form action="" method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
        </div>
        <button type="submit" class="btn">LOGIN</button>
    </form>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{%block title%}REGISTER{%endblock%}
{% block content %}
<h2>Register</h2>
<form method="POST">
    Username: <input type="text" name="username" required><br>
    Password: <input type="password" name="password" required><br>
    <button type="submit">Register</button>
</form>
{% endblock %}

app/templates/tasks.html
{% extends 'base.html' %}
{%block title%}TASKS{%endblock%}
{% block content %}


<div class="task-box">
    <h2>YOUR TASK</h2>
    <form action="{{url_for('tasks.add_task')}}" method="POST" class="task-form">
        <input type="text" name="title" placeholder="New task" required>
        <button type="submit" class="btn">Add</button>
    </form>

    {% if tasks %}
    <form action="{{url_for('tasks.clear_tasks')}}" method="post">
        <button type="submit" class="btn btn-clear">Clear All Tasks</button>
    </form>
    <br>
    <table class="tasks-table">
        <thead>
            <tr>
                <th>Task no.</th>
                <th>Task</th>
                <th>Status</th>
                <th>Change</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks%}
            <tr>
                <td>{{loop.index}}</td>
                <td>{{task.title}}</td>
                <td><span class="badge {{task.status | lower}}">{{task.status}}</span></td>
                <td>
                    <form action="{{url_for('tasks.toggle_status',task_id=task.id)}}" method="post">
                        <button type="submit" class="btn-small">Next</button>
                    </form>
                </td>
                <td>
                    <form action="{{ url_for('tasks.update_task', task_id=task.id) }}" method="POST">
                        <button class="btn btn-update" type="submit">Update</button>
                    </form>
                </td>
                <td>
                    <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST">
                        <button class="btn btn-delete" type="submit">Delete</button>
                    </form>

                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    {% else %}
    <p>No tasks yet.Add one above!</p>
    {%endif%}
</div>
{% endblock %}

app/templates/update.html
{% extends 'base.html' %}
{% block title %}Update Task{% endblock %}
{% block content %}

<div class="task-box">
    <h2>Update Task</h2>
    <form method="POST">
        <input type="text" name="title" value="{{ task.title }}" required>
        <button type="submit" class="btn">Update</button>
    </form>
</div>

{% endblock %}